version: '3'
services:
  your-service: 
    network_mode: host

  web:
    build: './web'
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: './db'
    ports:
      - "2701:2701"
